### PR TITLE
Issue 37: Avoid mixing commits from multiple branches

### PR DESCRIPTION
**Pull request by holgerknoche**
As suggested, the attached pull request emulates "--first-parent" behavior to avoid mixing commits from different concurrent branches.

### CODE REVIEW

**Comment by msteinbeck** [comment]
Thank you for this pull request. Could you please add these changes to the commit range based method too (`listRevisionsImpl(final String pFrom, final String pTo)`). Regarding the failing tests, I will merge you changes into a branch a fix them separately.

**Comment by holgerknoche** [comment]
I have unified the iteration behavior for both implementations of `listRevisionImpl`. However, this seems to break some tests in `JavaCPPTest` that I have not yet looked into.

**Comment by msteinbeck** [comment]
Hi @holgerknoche,

I was able to identify the error. It is caused by our generic Git tests which check whether a certain list of revisions is checked out in a specific order. Due to your changes, this list is not valid anymore because commits of merged branches are skipped (what is to be expected with your PR). I'll fix these tests later this day. Thank you for your PR. It is a great addition to this library.

**Comment by msteinbeck** [comment]
Finally I was able to fix all remaining issues. Thanks for this great PR. Sorry for the delay.

**Pull request closed without merging**
